# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage_app', '0006_garagemember'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='garage_app.GarageMember'),
            preserve_default=False,
        ),
    ]
